{% set data = load_setup_py_data() %}

package:
  name: "h2o-wave"
  version: "{{ VERSION }}"

about:
  home: https://h2o.ai/products/h2o-wave
  license: Apache License Version 2.0
  license_family: Apache
  summary: {{ data.get('description') }}
  description: |
    {{ data.get('conda_description') | replace('\n', '\n    ') }}

  dev_url: https://github.com/h2oai/wave
  doc_url: https://h2oai.github.io/wave/

requirements:
  build:
    - python={{ python_version }}
    - pip
    - wheel
    - Click
    - httpx==0.16.1
    - uvicorn==0.12.2
    - starlette==0.13.8

  run:
    - python={{ python_version }}
    - Click
    - httpx==0.16.1
    - uvicorn==0.12.2
    - starlette==0.13.8

source:
  path: ..

build:
  script: python setup.py install
  string: py{{ python_version | replace(".", "") }}