test:
	./gradlew test

build:
	./gradlew build

generate:
	./gradlew patchPluginXml

run:
	./gradlew runIde

verify:
	./gradlew runPluginVerifier

help:
	./gradlew -q :tasks --all

clean:
	./gradlew clean