#!/bin/bash

# Create the docs/examples directory if missing
mkdir -p docs/examples

# initialize examples.js
cat > examples.js << 'EOF'
// Auto-generated by generate_examples.sh
// Last updated: $(date)

module.exports = [
EOF

# process Py files
count=0
find ../py/examples -maxdepth 1 -name '*.py' ! -name '__init__.py' | while read -r pyfile; do
    filename=$(basename "$pyfile")
    slug=$(basename "$pyfile" .py | tr "_" "-")
    
    # Create md file
    cat > "docs/examples/${slug}.md" << EOM
# $(echo "$filename" | sed 's/_/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2)}1')

## Example Code
\`\`\`python
$(cat "$pyfile")
\`\`\`

## How to Run
\`\`\`bash
python ../py/examples/${filename}
\`\`\`
EOM

    # Add all to examples.js
    if [ $count -gt 0 ]; then
        echo "," >> examples.js
    fi
    echo "  { slug: '${slug}', file: '${filename}' }" >> examples.js
    ((count++))
done

# close the array
echo "]" >> examples.js

echo "Successfully generated:"
echo "- ${count} Markdown files in docs/examples/"
echo "- Updated examples.js"