
setup: 
	python3 -m venv venv
	./venv/bin/python -m pip install --upgrade pip
	./venv/bin/python -m pip install -r requirements.txt

run:
	./venv/bin/wave run web_ide.py --no-reload

clean:
	rm -rf venv