name: Publish Lightwave

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version'
        required: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VERSION: "${{ github.event.inputs.version }}"

jobs:
  publish:
    name: Publish Lightwave
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GIT_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Build lightwave
        run:  make publish-lightwave
      
      - name: Publish to PyPI - lightwave
        uses: pypa/gh-action-pypi-publish@master
        with:
          packages_dir: py/h2o_lightwave/dist
          password: ${{ secrets.PYPI_LIGTHWAVE_TOKEN }}

      - name: Publish to PyPI - lightwave_web
        uses: pypa/gh-action-pypi-publish@master
        with:
          packages_dir: py/h2o_lightwave_web/dist
          password: ${{ secrets.PYPI_LIGTHWAVE_WEB_TOKEN }}
